version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=dev-secret-key-change-in-production
      - DATABASE_URL=sqlite:///instance/database.db
    volumes:
      - .:/app
      - ./instance:/app/instance
    restart: unless-stopped


